# Generated by Django 4.0.4 on 2022-07-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_recipeinstruction_id_alter_recipeinstruction_r_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='recipeinstruction',
            constraint=models.UniqueConstraint(fields=('r_id', 'seq_no'), name='r_seq'),
        ),
    ]
